authors:
  jan:
    name: Jan Keijzer
    description: AI Automation Consultant | 30+ Years Mission-Critical Systems Experience
    avatar: ../../assets/profile.jpg
    url: https://www.linkedin.com/in/jankeijzer/